global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

        
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['scrape.leucinetech.com']
    
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      # cleen's
      - targets:
          - https://aizant.cleen.leucine.tech
          - https://alembic.cleen.leucine.tech
          - https://aurovitas.cleen.leucine.tech
          - https://biocon.cleen.leucine.tech
          - https://biocon.qa.cleen.leucinetech.com
          - https://cipla.cleen.leucine.tech
          - https://cipla.usa.cleen.leucine.tech
          - https://cronus.cleen.leucine.tech
          - https://encube.cleen.leucine.tech
          - https://eugia.cleen.leucine.tech
          - https://formulation.acme.cleen.leucine.tech
          - https://generics.acme.cleen.leucine.tech
          - https://granules.cleen.leucine.tech
          - https://guardian.cleen.leucinetech.com
          - https://immacule.cleen.leucine.tech
          - https://kusum.cleen.leucine.tech
          - https://mlab.cleen.leucine.tech
          - https://msn.cleen.leucine.tech
          - https://mydrreddys.cleen.leucinetech.com
          - https://onesource.cleen.leucine.tech
          - https://par.cleen.leucine.tech
          - https://pharmax.cleen.leucine.tech
          - https://pii.cleen.leucine.tech
          - https://piramal.cleen.leucine.tech
          - https://qa.cleen.leucinetech.com
          - https://stelis.cleen.leucine.tech
          - https://tenshi.cleen.leucine.tech
          - https://teva.cleen.leucine.tech
          - https://torrentpharma.cleen.leucine.tech
          - https://troikaa.cleen.leucine.tech
          - https://uat.cleen.leucinetech.com
          - https://zydus.cleen.leucine.tech
          - https://zyduscv.cleen.leucine.tech
        labels:
          team: cleen

      # dwi's / platform
      - targets:
          - https://api.amneal.platform.leucine.tech/v1/auth/account/lookup?username=system
          - https://api.andover.platform.leucine.tech/v1/auth/account/lookup?username=system
          - https://api.arcolab.platform.leucine.tech/v1/auth/account/lookup?username=system
          - https://api.cipla.platform.leucine.tech/v1/auth/account/lookup?username=system
          # - https://api.somerset.platform.leucine.tech/v1/auth/account/lookup?username=system
          - https://api.stelis.platform.leucine.tech/v1/auth/account/lookup?username=system
          - https://api.strides-us.platform.leucine.tech/v1/auth/account/lookup?username=system
          - https://api.strides.platform.leucine.tech/v1/auth/account/lookup?username=system
          - https://api.tenshi.platform.leucine.tech/v1/auth/account/lookup?username=system
          - https://api.valent.platform.leucine.tech/v1/auth/account/lookup?username=system
        labels:
          team: platform

      # others
      - targets:
          - https://acmegenerics.leucine.tech
          - https://piramal.eforms.leucine.tech
          - https://revlon-yuvi.leucine.ai
          - https://api.qa.platform.leucinetech.com/v1/auth/account/lookup?username=system
        labels:
          team: non-prod
        
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

#cleen-prods 
  - job_name: 'pharmax-production'
    static_configs:
      - targets: ['pharmax-production:9100']
        labels:
          server_ip: '20.40.60.169'
          server_name: 'pharmax-production'

  - job_name: 'aurovitas-production'
    static_configs:
      - targets: ['aurovitas-production:9100']
        labels:
          server_ip: '35.198.230.51'
          server_name: 'aurovitas-production'

  - job_name: 'acme-production'
    static_configs:
      - targets: ['acme-production:9100']
        labels:
          server_ip: '40.80.92.34'
          server_name: 'acme-production'
          
  - job_name: 'alkem-production'
    static_configs:
      - targets: ['alkem-production:9100']
        labels:
          server_ip: '98.70.42.140'
          server_name: 'alkem-production'
          
  - job_name: 'aizant-production'
    static_configs:
      - targets: ['aizant-production:9100']
        labels:
          server_ip: '20.40.56.171'
          server_name: 'aizant-production'

  - job_name: 'alembic-production'
    static_configs:
      - targets: ['alembic-production:9100']
        labels:
         server_ip: '20.193.224.204'
         server_name: 'alembic-production'

  - job_name: 'cipla-production'
    static_configs:
      - targets: ['cipla-production:9100']
        labels:
          server_ip: '4.240.87.136'
          server_name: 'cipla-production'


  - job_name: 'biocon-production'
    static_configs:
      - targets: ['biocon-production:9100']
        labels:
          server_ip: '20.244.95.3'
          server_name: 'biocon-production'

  - job_name: 'cipla-usa-production'
    static_configs:
      - targets: ['cipla-usa-production:9100']
        labels:
          server_ip: '13.87.246.226'
          server_name: 'cipla-usa-production'

  - job_name: 'cronus-production'
    static_configs:
      - targets: ['cronus-production:9100']
        labels:
          server_ip: '40.81.243.57'
          server_name: 'cronus-production'

  - job_name: 'mydrreddys-production'
    static_configs:
      - targets: ['mydrreddys-production:9100']
        labels:
          server_ip: '20.40.60.109'
          server_name: 'mydrreddys-production'

  - job_name: 'encube-production'
    static_configs:
      - targets: ['encube-production:9100']
        labels:
          server_ip: '20.244.25.217'
          server_name: 'encube-production'

  - job_name: 'par-production'
    static_configs:
      - targets: ['par-production:9100']
        labels:
          server_ip: '4.240.84.31'
          server_name: 'par-production'

  - job_name: 'eugia-production'
    static_configs:
      - targets: ['eugia-production:9100']
        labels:
          server_ip: '20.244.42.224'
          server_name: 'eugia-production'

  - job_name: 'granules-production'
    static_configs:
      - targets: ['granules-production:9100']
        labels:
          server_ip: '20.245.222.129'
          server_name: 'granules-production'

  - job_name: 'guardian-production'
    static_configs:
      - targets: ['guardian-production:9100']
        labels:
          server_ip: '20.40.59.52'
          server_name: 'guardian-production'

  - job_name: 'kusum-production'
    static_configs:
      - targets: ['kusum-production:9100']
        labels:
          server_ip: '20.244.8.45'
          server_name: 'kusum-production'

  - job_name: 'mlab-production'
    static_configs:
      - targets: ['mlab-production:9100']
        labels:
          server_ip: '20.244.27.161'
          server_name: 'mlab-production'

  - job_name: 'msn-production'
    static_configs:
      - targets: ['msn-production:9100']
        labels:
          server_ip: '52.172.231.143'
          server_name: 'msn-production'

  - job_name: 'pii-production'
    static_configs:
      - targets: ['pii-production:9100']
        labels:
          server_ip: '40.118.252.13'
          server_name: 'pii-production'

  - job_name: 'piramal-production'
    static_configs:
      - targets: ['piramal-production:9100']
        labels:
          server_ip: '4.240.81.119'
          server_name: 'piramal-production'

  - job_name: 'stelis-production'
    static_configs:
      - targets: ['stelis-production:9100']
        labels:
          server_ip: '20.40.57.115'
          server_name: 'stelis-production'

  - job_name: 'onesource-production'
    static_configs:
      - targets: ['onesource-production:9100']
        labels:
          server_ip: '98.70.88.64'
          server_name: 'onesource-production'

  - job_name: 'tenshi-production'
    static_configs:
      - targets: ['tenshi-production:9100']
        labels:
          server_ip: '20.244.0.34'
          server_name: 'tenshi-production'

  - job_name: 'teva-production'
    static_configs:
      - targets: ['teva-production:9100']
        labels:
          server_ip: '20.217.81.45'
          server_name: 'teva-production'

  - job_name: 'torrentpharma-production'
    static_configs:
      - targets: ['torrent-production:9100']
        labels:
          server_ip: '40.81.244.238'
          server_name: 'torrentpharma-production'

  - job_name: 'troikaa-production'
    static_configs:
      - targets: ['troikaa-production:9100']
        labels:
          server_ip: '40.81.241.106'
          server_name: 'troikaa-production'


  - job_name: 'zyduscv-production'
    static_configs:
      - targets: ['zyduscv-production:9100']
        labels:
          server_ip: '20.244.44.109'
          server_name: 'zyduscv-production'


#platform-prods
  - job_name: 'amneal-dwi-production'
    static_configs:
      - targets: ['amneal-dwi-production:9100']
        labels:
          server_ip: '4.240.94.210'
          server_name: 'amneal-dwi-production'

  - job_name: 'tenshi-dwi-production'
    static_configs:
      - targets: ['tenshi-dwi-production:9100']
        labels:
          server_ip: '98.70.15.31'
          server_name: 'tenshi-dwi-production'


  - job_name: 'zydus-dwi-production'
    static_configs:
      - targets: ['zydus-dwi-production:9100']
        labels:
          server_ip: '4.186.63.1'
          server_name: 'zydus-dwi-production'


#non-prods
  - job_name: 'platform-qa-server'
    static_configs:
      - targets: ['node.leucinetech.com']
        labels:
          server_ip: '34.93.160.186'
          server_name: 'platform-qa-server'          



























# rule_files:
#   - "alert.rules.yml"
