server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: monitoring-server
          __path__: /var/log/*.log

  - job_name: caddy-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: caddylogs
          host: monitoring-server
          __path__: /var/log/caddy/*.log

  - job_name: dwi
    static_configs:
      - targets:
          - localhost
        labels:
          job: dwilogs
          host: monitoring-server
          __path__: /tmp/log/leucine/dev/main/dwi/*.log
