global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

        
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['scrape.leucinetech.com']
    
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://uat.cleen.leucinetech.com
        - https://qa.cleen.leucinetech.com
        - https://biocon.qa.cleen.leucinetech.com
        - https://jenkins.leucinetech.com
        - https://immacule.cleen.leucine.tech
        - https://generics.acme.cleen.leucine.tech
        - https://formulation.acme.cleen.leucine.tech
        - https://pharmax.cleen.leucine.tech
        - https://acmegenerics.leucine.tech
        - https://andover.platform.leucine.tech
        - https://aurovitas.cleen.leucine.tech
        - https://aizant.cleen.leucine.tech
        - https://alembic.cleen.leucine.tech
        - https://amneal.platform.leucine.tech
        - https://arcolab.platform.leucine.tech
        - https://cipla.cleen.leucine.tech
        - https://biocon.cleen.leucine.tech
        - https://cipla.usa.cleen.leucine.tech
        - https://cipla.platform.leucine.tech
        - https://cronus.cleen.leucine.tech
        - https://mydrreddys.cleen.leucinetech.com
        - https://encube.cleen.leucine.tech
        - https://par.cleen.leucine.tech
        - https://eugia.cleen.leucine.tech
        - https://granules.cleen.leucine.tech
        - https://guardian.cleen.leucinetech.com
        - https://kusum.cleen.leucine.tech
        - https://mlab.cleen.leucine.tech
        - https://msn.cleen.leucine.tech
        - https://pii.cleen.leucine.tech
        - https://piramal.eforms.leucine.tech
        - https://piramal.cleen.leucine.tech
        - https://revlon-yuvi.leucine.ai
        - https://somerset.platform.leucine.tech
        - https://stelis.cleen.leucine.tech
        - https://stelis.platform.leucine.tech
        - https://onesource.cleen.leucine.tech
        - https://strides-us.platform.leucine.tech
        - https://strides.platform.leucine.tech
        - https://tenshi.cleen.leucine.tech
        - https://tenshi.platform.leucine.tech
        - https://teva.cleen.leucine.tech
        - https://torrentpharma.cleen.leucine.tech
        - https://troikaa.cleen.leucine.tech
        - https://valent.platform.leucine.tech
        - https://report.valent.platform.leucine.tech
        - https://zydus.cleen.leucine.tech
        - https://zyduscv.cleen.leucine.tech
        
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'Grafana-Server'
    static_configs:
      - targets: ['grafana-server:9100']
        labels:
          server_ip: '52.66.38.198'
          server_name: 'grafana-server'

  - job_name: 'prometheus-server'
    static_configs:
      - targets: ['prometheus-server:9100']
        labels:
          server_ip: '13.204.64.137'
          server_name: 'prometheus-server'

  - job_name: 'Promtail-NE'
    static_configs:
      - targets: ['13.235.42.208:9100']
        labels:
          server_ip: '13.235.42.208'
          server_name: 'Promtail-NE'

  - job_name: 'platform-qa-server'
    static_configs:
      - targets: ['node.leucinetech.com']
        labels:
          server_ip: '34.93.160.186'
          server_name: 'platform-qa-server'          

  - job_name: 'cleen-biocon-server'
    static_configs:
      - targets: ['biocon-server:9100']
        labels:
          server_ip: '20.244.95.3'
          server_name: 'cleen-biocon-server'   

  - job_name: 'acme-production-server'
    static_configs:
      - targets: ['acme-server:9100']
        labels:
          server_ip: '40.80.92.34'
          server_name: 'acme-production-server'
# rule_files:
#   - "alert.rules.yml"
