server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo

compactor:
  compaction:
    compacted_block_retention: 48h
