#version: '3.8'

services:
  init-perms:
    image: alpine
    container_name: init-perms
    user: root
    command: >
      sh -c "
        echo '📂 Fixing ownership of data-volumes...' && \
        adduser -D tempuser && \
        chown -R 472:472 /data/grafana && \
        chown -R 65534:65534 /data/prometheus && \
        chown -R 10001:10001 /data/loki && \
        chown -R tempuser:tempuser /data/promtail && \
        chown -R 10000:10000 /data/tempo && \
        echo '✅ Permissions fixed.'
      "
    volumes:
      - ./data-volumes/grafana:/data/grafana
      - ./data-volumes/prometheus:/data/prometheus
      - ./data-volumes/loki:/data/loki
      - ./data-volumes/promtail:/data/promtail
      - ./data-volumes/tempo:/data/tempo
    restart: "no"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - init-perms
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning
      - ./data-volumes/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=fhbv@4JUbkgmb
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - init-perms
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data-volumes/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: loki
    depends_on:
      - init-perms
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./config/loki.yml:/etc/loki/loki.yml
      - ./data-volumes/loki:/var/lib/loki
    restart: always

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    depends_on:
      - init-perms
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./config/promtail.yml:/etc/promtail/promtail.yml
      - /var/log:/var/log
      - ./data-volumes/promtail:/promtail
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: always

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./config/blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    restart: always

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    depends_on:
      - init-perms
    ports:
      - "3200:3200"   # HTTP API for Tempo
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    volumes:
      - ./config/tempo.yml:/etc/tempo/tempo.yml
      - ./data-volumes/tempo:/tmp/tempo
    restart: always

networks:
  default:
    name: monitor-net
